### ISSUE TITLE
OpenQAOA dependency does not support python 3.11

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/aquapointer#63]
OpenQAOA, a dependency, does not support python 3.11, so installing it brings an error. If not used, OpenQAOA could be removed.

**Comment by Misty-W** [comment]
Fixed in [42f07b7](https://github.com/unitaryfund/aquapointer/commit/42f07b700b8fac5567e81ed8121f73ed5f867cba).

**Comment by nathanshammah** [comment]
Great!
