### ISSUE TITLE
force_lattice_size error if fewer points placed than size user wants to force

### ISSUE THREAD

**Issue by darcangelomauro** [unitaryfund/aquapointer#82]
See title

**Comment by darcangelomauro** [comment]
The issue was fixed in #84. The problem was the code was selecting the first qubit to cut, but if no qubit has to be cut, then you would get the `KeyError`. So now the code selects the first qubit to keep, which always exists.

**Comment by nathanshammah** [comment]
Has this been fixed by #84?

**Comment by Misty-W** [comment]
Fixed by #84.
