### ISSUE TITLE
Lattice coordinates are sometimes too close to each other

### ISSUE THREAD

**Issue by darcangelomauro** [unitaryfund/aquapointer#85]
Possible solution is to introduce a new set of coordinates to calculate detunings and do pulser simulations.

To do:
1- Getter function on canvas that takes as input an optional "minimal distance" arguments. Returns lattice coordinates scaled so that the minimal distance is the one provided
2- Use that getter in `calculate_detunings`

Use the getter to build the register in automated script

**Comment by Misty-W** [comment]
Fixed in #84.
